Bubble-sort algorithm
evabanegacom/Bubble_sort pull request #1
Opened 2020-04-16 09:25 UTC by evabanegacom

This is an algorithm that sorts arrays in a pair format, comparing the previous element with the next one
we  have
written a bubble sort algorithm for sorting
and using yield as well to compare array characters based on size.

2020-04-16 17:35 UTC, mosesogwo requested changes
**Hi @evabanegacom, @karthi07:clap:, Good work on this project. :+1:**

_**Please see my comment on the bubble_sort_by method, make the change, and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-04-16 17:35 UTC, mosesogwo commented on bubble_sort.rb
> +  print array
Your method should return the sorted array and not print it. As it is now, it returns nil.

2020-04-16 17:35 UTC, mosesogwo commented on bubble_sort.rb
> +end
You can remove these lines of code once you have verified that your methods are working correctly.

2020-04-16 19:57 UTC, evabanegacom commented
i have fixed the return function issue

2020-04-17 03:38 UTC, euqueme approved these changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @evabanegacom and @karthi07  :balloon: :lollipop: 

### You've done all the changes and your project works as expected so you may move on Congratulations! :heavy_check_mark: :heavy_check_mark: :heavy_check_mark: 

PROJECT STATUS: APPROVED :green_apple:

2020-04-17 08:50 UTC, merged